<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HDC0005363" ignored="0" name="RetryMultipleFailedTestCases" tests="9" failures="2" timestamp="14 Jun 2018 14:03:39 GMT" time="0.08" errors="0">
  <testcase name="Test1" time="0.015" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.004" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test1 -->
  <testcase name="Test1" time="0.002" classname="retryLogic.RetryLogicFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at retryLogic.RetryLogicFailedTestCases.Test1(RetryLogicFailedTestCases.java:10)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test1 -->
  <testcase name="Test2" time="0.005" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.0" classname="retryLogic.RetryLogicFailedTestCases">
    <skipped/>
  </testcase> <!-- Test2 -->
  <testcase name="Test2" time="0.001" classname="retryLogic.RetryLogicFailedTestCases">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
	at retryLogic.RetryLogicFailedTestCases.Test2(RetryLogicFailedTestCases.java:15)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test2 -->
  <testcase name="Test3" time="0.002" classname="retryLogic.RetryLogicFailedTestCases"/>
</testsuite> <!-- RetryMultipleFailedTestCases -->
